mod engine;
pub(crate) mod events;
mod legacy_notify;
mod registry;
mod schema;
mod session_end;
mod types;

pub use events::post_tool_use::PostToolUseOutcome;
pub use events::post_tool_use::PostToolUseRequest;
pub use events::pre_tool_use::PreToolUseOutcome;
pub use events::pre_tool_use::PreToolUseRequest;
pub use events::session_start::SessionStartOutcome;
pub use events::session_start::SessionStartRequest;
pub use events::session_start::SessionStartSource;
pub use events::stop::StopOutcome;
pub use events::stop::StopRequest;
pub use events::user_prompt_submit::UserPromptSubmitOutcome;
pub use events::user_prompt_submit::UserPromptSubmitRequest;
pub use legacy_notify::legacy_notify_json;
pub use legacy_notify::notify_hook;
pub use registry::Hooks;
pub use registry::HooksConfig;
pub use registry::command_from_argv;
pub use schema::write_schema_fixtures;
pub use session_end::session_end_transcript_path_from_json;
pub use types::CommandHookConfig;
pub use types::Hook;
pub use types::HookEvent;
pub use types::HookEventAfterAgent;
pub use types::HookEventAfterToolUse;
pub use types::HookEventSessionEnd;
pub use types::HookEventSubagentStart;
pub use types::HookEventSubagentStop;
pub use types::HookEventUserPromptSubmit;
pub use types::HookExecutionOutcome;
pub use types::HookPayload;
pub use types::HookPermissionDecision;
pub use types::HookResponse;
pub use types::HookResult;
pub use types::HookRuleConfig;
pub use types::HookToolInput;
pub use types::HookToolInputLocalShell;
pub use types::HookToolKind;
pub use types::HooksToml;
